config/routes.rb
Pooling::Application.routes.draw do
  
  resources :casualcomments

  resources :regularcomments

  resources :casualsubscriptions

  resources :regularsubscriptions

  resources :regularshares

  resources :casualshares

  resources :places

  resources :cities

  get "gmaps/index"

  resources :password_resets, :only =>[ :new, :create, :edit, :update ]
  resources :users, :user_sessions
  
  
  match 'signup' => 'users#new'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'confirmation' => 'users#confirmation' 
  match 'home' => 'users#profile'

  root :to => 'users#new'

end

app/models/regularcomment.rb
class Regularcomment < ActiveRecord::Base

	belongs_to :regularshare
	belongs_to :user

end

app/controllers/regularcomments_controller.rb
class RegularcommentsController < ApplicationController
  # GET /regularcomments
  # GET /regularcomments.json
  def index
    @regularcomments = Regularcomment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @regularcomments }
    end
  end

  # GET /regularcomments/1
  # GET /regularcomments/1.json
  def show
    @regularcomment = Regularcomment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @regularcomment }
    end
  end

  # GET /regularcomments/new
  # GET /regularcomments/new.json
  def new
    @regularcomment = Regularcomment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @regularcomment }
    end
  end

  # GET /regularcomments/1/edit
  def edit
    @regularcomment = Regularcomment.find(params[:id])
  end

  # POST /regularcomments
  # POST /regularcomments.json
  def create
    @regularcomment = Regularcomment.new(params[:regularcomment])

      if @regularcomment.save
	redirect_to Regularshare.find(@regularcomment.regularshare_id), notice: 'Regularcomment was successfully created.' 
      else
        redirect_to Regularshare.find(@regularcomment.regularshare_id), notice: 'Please try again.' 
      end

  end

  # PUT /regularcomments/1
  # PUT /regularcomments/1.json
  def update
    @regularcomment = Regularcomment.find(params[:id])

    respond_to do |format|
      if @regularcomment.update_attributes(params[:regularcomment])
        format.html { redirect_to @regularcomment, notice: 'Regularcomment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @regularcomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regularcomments/1
  # DELETE /regularcomments/1.json
  def destroy
    @regularcomment = Regularcomment.find(params[:id])
    @regularshare = @regularcomment.regularshare
    
    @regularcomment.destroy
    redirect_to @regularshare, notice: 'Regularcomment was successfully delteed.'  

  end
end

app/helpers/regularcomments_helper.rb
module RegularcommentsHelper
end

app/views/regularcomments/_form.html.erb
<%= form_for(@regularcomment) do |f| %>
  <% if @regularcomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regularcomment.errors.count, "error") %> prohibited this regularcomment from being saved:</h2>

      <ul>
      <% @regularcomment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :regularshare_id %><br />
    <%= f.number_field :regularshare_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regularcomments/_regularcomment.html.erb
<tr>
<td class="micropost">
<%= link_to @regularcomment.user.firstname, @regularcomment.user %> : 
<span class="content"><%= regularcomment.details %></span><br/>

<span class="timestamp">Posted <%= time_ago_in_words(regularcomment.created_at) %> ago.
</span>
<% if current_user == regularcomment.user %>
<%= link_to "delete", regularcomment, :method => :delete,
:confirm => "You sure?",
:title => regularcomment.details %>
</td>
<% end %>
</tr>

app/views/regularcomments/edit.html.erb
<h1>Editing regularcomment</h1>

<%= render 'form' %>

<%= link_to 'Show', @regularcomment %> |
<%= link_to 'Back', regularcomments_path %>

app/views/regularcomments/index.html.erb
<h1>Listing regularcomments</h1>

<table>
  <tr>
    <th>Regularshare</th>
    <th>User</th>
    <th>Details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @regularcomments.each do |regularcomment| %>
  <tr>
    <td><%= regularcomment.regularshare_id %></td>
    <td><%= regularcomment.user_id %></td>
    <td><%= regularcomment.details %></td>
    <td><%= link_to 'Show', regularcomment %></td>
    <td><%= link_to 'Edit', edit_regularcomment_path(regularcomment) %></td>
    <td><%= link_to 'Destroy', regularcomment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Regularcomment', new_regularcomment_path %>

app/views/regularcomments/new.html.erb
<h1>New regularcomment</h1>

<%= render 'form' %>

<%= link_to 'Back', regularcomments_path %>

app/views/regularcomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Regularshare:</b>
  <%= @regularcomment.regularshare_id %>
</p>

<p>
  <b>User:</b>
  <%= @regularcomment.user_id %>
</p>

<p>
  <b>Details:</b>
  <%= @regularcomment.details %>
</p>


<%= link_to 'Edit', edit_regularcomment_path(@regularcomment) %> |
<%= link_to 'Back', regularcomments_path %>