config/routes.rb
Pooling::Application.routes.draw do
  
  resources :casualcomments

  resources :regularcomments

  resources :casualsubscriptions

  resources :regularsubscriptions

  resources :regularshares

  resources :casualshares

  resources :places

  resources :cities

  get "gmaps/index"

  resources :password_resets, :only =>[ :new, :create, :edit, :update ]
  resources :users, :user_sessions
  
  
  match 'signup' => 'users#new'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'confirmation' => 'users#confirmation' 
  match 'home' => 'users#profile'

  root :to => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_authentic

   #associations-------------------
	belongs_to :city
	has_many :casualshares, :dependent => :destroy
	has_many :regularshares, :dependent => :destroy
	has_many :casualsubscriptions, :dependent => :destroy
	has_many :regularsubscriptions, :dependent => :destroy
	has_many :casualcomments, :dependent => :destroy					
	has_many :regularcomments, :dependent => :destroy				




   #-------------------------------
   #VALIDATIONS--------------------
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :username,  :presence => true, :length => { :in => 3..20 }
    validates :lastname,  :presence => true
    validates :firstname,  :presence => true
    validates :email, :presence => true,
                     :format => { :with => email_regex },
                     :uniqueness => { :case_sensitive => false }
    validates :city, :presence => true
    
    validates :password, :presence => true,
                         :confirmation => true,
                         :length => { :within => 2..40 }

    
    #before_save :encrypt_password
    
    validates :sex,  :presence => true
    validates :dateofbirth,  :presence => true
    validates :phonenumber,  :presence => true, :numericality => true
    


   #-------------------------------
   def deliver_password_reset_instructions!
     reset_perishable_token!
     Notifier.deliver_password_reset_instructions(self)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate, :except => [ :new, :create, :confirm , :confirmation ]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => [:destroy, :index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(@current_user.id)
    @regularsubscriptions = @current_user.regularsubscriptions
    @casualsubscriptions = @current_user.casualsubscriptions
  end

  def new
    redirect_to home_url if signed_in?
    @user = User.new
  end

  
  def create
    @user = User.new(params[:user])
    @user.confirmation = String.random_alphanumeric(10)
    
    if @user.save
	UserMailer.welcome_email(@user).deliver
	flash[:success] = "Please Check you mail and activate you account"
	redirect_to  login_path
    else
	render :action => "new"
    end
    
  end

  def confirmation
     @user = User.new(params[:user])
	render :layout => nil
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

      if @user.update_attributes(params[:user])
	flash[:success] = "User was successfully updated."
	redirect_to @user 
      else
        render :action => "edit"
      end

  end

  def passwordedit
    @user = User.find(params[:id])
  end

  def passwordupdate
    @user = User.find(params[:id])

      if @user.update_attributes(params[:user])
         redirect_to @user, :notice => "User was successfully updated."
      else
        render :action => "edit"
      end

  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    @user.signout
    redirect_to signin_url
  end

  private
    def String.random_alphanumeric(size=16)
  	s = ""
  	size.times { s << (i = Kernel.rand(62); i += ((i < 10) ? 48 : ((i < 36) ? 55 : 61 ))).chr }
  	s
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_editform.html.erb
 <% @cities = City.all %>
 <% cou = @cities.count %>
 <% arr = Array.new(cou) { Array.new(2) } %>
 <% for n in 1..cou %>
 <% arr[n-1][0] = @cities[n-1].cityname %>
 <% arr[n-1][1] = n %>
 <% end %>
 <% arr %>



<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table border="0" width="400">
    <TR><TD width=" "> First Name</td>
    <td width="50%"><%= f.text_field :firstname %>
    </TD></TR>
 
 
    <TR><TD>
    Last Name</td><td>
    <%= f.text_field :lastname %></TD></TR>
     
   <TR><TD>
  <%= f.label :password %></td><td>
  <%= f.password_field :password %></TD></TR>
 
   <TR><TD>
  <%= f.label :password_confirmation, "Confirm Password" %></td><td>
  <%= f.password_field :password_confirmation %></TD></TR>
 
   <TR><TD>
    <%= f.label :city %></td><td>
    <%= f.select(:city_id, arr ) %></TD></TR>

    <TR><TD>
    <%= f.label :sex %></td><td>
    <%= f.select( :sex, [["Male", "Male"], ["Female", "Female"]])%></TD></TR>

    <TR><TD>
    <%= f.label :dateofbirth %></td><td>
    <%= f.date_select( :dateofbirth,:date_separator => "-" , :start_year => 1960 ) %></TD></TR>
 <TR><TD>
    <%= f.label :phonenumber %></td><td>
    <%= f.text_field :phonenumber %></TD></TR>
 </table>
<input id="lastloginip" name="user[lastloginip]" type="hidden" value="<%= request.remote_addr %>" />
 
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/_form.html.erb
 <% @cities = City.all %>
 <% cou = @cities.count %>
 <% arr = Array.new(cou) { Array.new(2) } %>
 <% for n in 1..cou %>
 <% arr[n-1][0] = @cities[n-1].cityname %>
 <% arr[n-1][1] = n %>
 <% end %>
 <% arr %>

<script type="text/javascript" charset="utf-8">
    $(function(){
	$('.date-pick').datePicker({clickInput:true})
    });
</script>


<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
       <p> &nbsp;&nbsp;&nbsp;<%= @user.errors.full_messages[0] %></p>
    </div>
  <% end %>
  <table border="0" width="400">
    <TR><TD width=" "> First Name</td>
    <td width="50%"><%= f.text_field :firstname %>
    </TD></TR>
 
 
    <TR><TD>
    Last Name</td><td>
    <%= f.text_field :lastname %></TD></TR>
    <TR><TD>
    <%= f.label :usernmae %></td><td>
    <%= f.text_field :username %></TD></TR>
    <TR><TD>
    <%= f.label :email %></td><td>
    <%= f.text_field :email %></TD></TR>
 
   <TR><TD>
  <%= f.label :password %></td><td>
  <%= f.password_field :password %></TD></TR>
 
   <TR><TD>
  <%= f.label :password_confirmation, "Confirm Password" %></td><td>
  <%= f.password_field :password_confirmation %></TD></TR>
 
   <TR><TD>
    <%= f.label :city %></td><td>
    <%= f.select(:city_id, arr ) %></TD></TR>

    <TR><TD>
    <%= f.label :sex %></td><td>
    <%= f.select( :sex, [["Male", "Male"], ["Female", "Female"]])%></TD></TR>

    <TR><TD>
    <%= f.label :dateofbirth %></td><td>
    <%= f.date_select( :dateofbirth,:date_separator => "-" , :start_year => 1960 ) %></TD></TR>
 <TR><TD>
    <%= f.label :phonenumber %></td><td>
    <%= f.text_field :phonenumber %></TD></TR>
 </table>
<input id="lastloginip" name="user[lastloginip]" type="hidden" value="<%= request.remote_addr %>" />
 
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/confirmation.html.erb
<% @user = User.find_by_confirmation(params[:confirmation])
    if !@user.nil?	
      if !@user.active?
	if @user.toggle!(:active) %>
         <%=  "Registration successful, Please login to continue" %>
           
        <% else 
           render 'confirmation'
     	end
      else %>
	<%= "Your Account is already active." %>
     <% end
    else %>
	<%=  "Given Link doesnt exist. Please check carefully" %>
 <% end %>


<% 
if !@user.nil?
if @user.active? %>
 <%= link_to "Login Here", login_url %>
<% end end %> 

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'editform' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>



<% request.remote_ip %><br/>
<% request.remote_addr %>

app/views/users/profile.html.erb
<p>
  Hi
  <b><%= @user.firstname %> <%= @user.lastname %></b>,
  <%= "This is your home page" %>
</p>

<table border=1 width=1000>
<tr><td>
<h4>Regular Share Subscriptios By You :</h4>
<% @regularsubscriptions.each do |regularsubscription| %>
    <p> <%= link_to "Regularshare", regularsubscription.regularshare %><br/>
     Current Status : 
    <b><% if regularsubscription.status? %> Confirmed <% else %> Waiting <% end %><br/></b>
    Details : <%= regularsubscription.details %><br/>
<% end %>
</td></tr>
<tr><td>
<h4>Casual Share Subscriptios By You :</h4>

<% @casualsubscriptions.each do |casualsubscription| %>
    <p> <%= link_to "Casualshare", casualsubscription.casualshare %><br/>
     Current Status : 
    <b><% if casualsubscription.status? %> Confirmed <% else %> Waiting <% end %><br/></b>
    Details : <%= casualsubscription.details %><br/>
<% end %>

</td></tr>
<tr><td></td></tr>
<tr><td></td></tr>
</table>
<%= link_to 'Casual Shares', casualshares_path %> | 
<%= link_to 'Regular Shares', regularshares_path %>

app/views/users/show.html.erb
<p>
  Hi
  <%= @user.username %>,
  <%= "This is your home page" %>
</p>