config/routes.rb
Pooling::Application.routes.draw do
  
  resources :casualcomments

  resources :regularcomments

  resources :casualsubscriptions

  resources :regularsubscriptions

  resources :regularshares

  resources :casualshares

  resources :places

  resources :cities

  get "gmaps/index"

  resources :password_resets, :only =>[ :new, :create, :edit, :update ]
  resources :users, :user_sessions
  
  
  match 'signup' => 'users#new'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'confirmation' => 'users#confirmation' 
  match 'home' => 'users#profile'

  root :to => 'users#new'

end

app/models/casualsubscription.rb
class Casualsubscription < ActiveRecord::Base

	belongs_to :casualshare
	belongs_to :user

end

app/controllers/casualsubscriptions_controller.rb
class CasualsubscriptionsController < ApplicationController
  # GET /casualsubscriptions
  # GET /casualsubscriptions.json
  def index
    @casualsubscriptions = Casualsubscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @casualsubscriptions }
    end
  end

  # GET /casualsubscriptions/1
  # GET /casualsubscriptions/1.json
  def show
    @casualsubscription = Casualsubscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @casualsubscription }
    end
  end

  # GET /casualsubscriptions/new
  # GET /casualsubscriptions/new.json
  def new
    @casualsubscription = Casualsubscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @casualsubscription }
    end
  end

  # GET /casualsubscriptions/1/edit
  def edit
    @casualsubscription = Casualsubscription.find(params[:id])
  end

  # POST /casualsubscriptions
  # POST /casualsubscriptions.json
  def create
    @casualsubscription =  Casualsubscription.new(params[:casualsubscription])
    @casualsubscription.status = false
      if @casualsubscription.save
        redirect_to Casualshare.find(@casualsubscription.casualshare_id), notice: 'Casualsubscription was successfully created.' 
      else
        redirect_to Casualshare.find(@casualsubscription.casualshare_id), notice: 'Please try again.' 
      end

  end

  # PUT /casualsubscriptions/1
  # PUT /casualsubscriptions/1.json
  def update
    @casualsubscription = Casualsubscription.find(params[:id])

    respond_to do |format|
      if @casualsubscription.update_attributes(params[:casualsubscription])
        format.html { redirect_to @casualsubscription, notice: 'Casualsubscription was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @casualsubscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casualsubscriptions/1
  # DELETE /casualsubscriptions/1.json
  def destroy
    @casualsubscription = Casualsubscription.find(params[:id])
    @casualsubscription.destroy

    respond_to do |format|
      format.html { redirect_to casualsubscriptions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/casualsubscriptions_helper.rb
module CasualsubscriptionsHelper
end

app/views/casualsubscriptions/_casualsubscription.html.erb
<tr>
<td class="micropost">
<%= link_to @casualsubscription.user.firstname, @casualsubscription.user %> : 
<span class="content"><%= casualsubscription.details %></span><br/>
<span class="content"><%= "Amount : " %><b><%= casualsubscription.amount %></b></span>&nbsp;&nbsp;&nbsp;
<span class="content"><%= "Passngrs : " %><b><%= casualsubscription.passengers %></b></span>&nbsp;&nbsp;&nbsp;

<span class="timestamp">Posted <%= time_ago_in_words(casualsubscription.created_at) %> ago.
</span>
<% if current_user == casualsubscription.user %>
<%= link_to "delete", casualsubscription, :method => :delete,
:confirm => "You sure?",
:title => casualsubscription.details %>
</td>
<% end %>
</tr>

app/views/casualsubscriptions/_form.html.erb
<%= form_for(@casualsubscription) do |f| %>
  <% if @casualsubscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@casualsubscription.errors.count, "error") %> prohibited this casualsubscription from being saved:</h2>

      <ul>
      <% @casualsubscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :casualshare_id %><br />
    <%= f.number_field :casualshare_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :passengers %><br />
    <%= f.number_field :passengers %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/casualsubscriptions/edit.html.erb
<h1>Editing casualsubscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @casualsubscription %> |
<%= link_to 'Back', casualsubscriptions_path %>

app/views/casualsubscriptions/index.html.erb
<h1>Listing casualsubscriptions</h1>

<table>
  <tr>
    <th>User</th>
    <th>Casualshare</th>
    <th>Amount</th>
    <th>Passengers</th>
    <th>Status</th>
    <th>Details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @casualsubscriptions.each do |casualsubscription| %>
  <tr>
    <td><%= casualsubscription.user_id %></td>
    <td><%= casualsubscription.casualshare_id %></td>
    <td><%= casualsubscription.amount %></td>
    <td><%= casualsubscription.passengers %></td>
    <td><%= casualsubscription.status %></td>
    <td><%= casualsubscription.details %></td>
    <td><%= link_to 'Show', casualsubscription %></td>
    <td><%= link_to 'Edit', edit_casualsubscription_path(casualsubscription) %></td>
    <td><%= link_to 'Destroy', casualsubscription, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Casualsubscription', new_casualsubscription_path %>

app/views/casualsubscriptions/new.html.erb
<h1>New casualsubscription</h1>

<%= render 'form' %>

<%= link_to 'Back', casualsubscriptions_path %>

app/views/casualsubscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @casualsubscription.user_id %>
</p>

<p>
  <b>Casualshare:</b>
  <%= @casualsubscription.casualshare_id %>
</p>

<p>
  <b>Amount:</b>
  <%= @casualsubscription.amount %>
</p>

<p>
  <b>Passengers:</b>
  <%= @casualsubscription.passengers %>
</p>

<p>
  <b>Status:</b>
  <%= @casualsubscription.status %>
</p>

<p>
  <b>Details:</b>
  <%= @casualsubscription.details %>
</p>


<%= link_to 'Edit', edit_casualsubscription_path(@casualsubscription) %> |
<%= link_to 'Back', casualsubscriptions_path %>