config/routes.rb
Pooling::Application.routes.draw do
  
  resources :casualcomments

  resources :regularcomments

  resources :casualsubscriptions

  resources :regularsubscriptions

  resources :regularshares

  resources :casualshares

  resources :places

  resources :cities

  get "gmaps/index"

  resources :password_resets, :only =>[ :new, :create, :edit, :update ]
  resources :users, :user_sessions
  
  
  match 'signup' => 'users#new'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'confirmation' => 'users#confirmation' 
  match 'home' => 'users#profile'

  root :to => 'users#new'

end

app/models/casualshare.rb
class Casualshare < ActiveRecord::Base

	belongs_to :user
	has_many :casualsubscriptions, :dependent => :destroy
	has_many :casualcomments, :dependent => :destroy
end

app/controllers/casualshares_controller.rb
class CasualsharesController < ApplicationController
  # GET /casualshares
  # GET /casualshares.json
  def index
    @casualshares = Casualshare.all
  end


  def show
    @casualshare = Casualshare.find(params[:id])

    @casualsubscription = current_user.casualsubscriptions.build(params[:casualsubscription])
    @casualsubscriptions = Casualsubscription.where("casualshare_id=?", params[:id]).order('created_at DESC')

    @casualcomment = current_user.casualcomments.build(params[:casualcomment])
    @casualcomments = Casualcomment.where("casualshare_id=?", params[:id]).order('created_at DESC')

  end

  def new
    @casualshare = Casualshare.new
  end

  # GET /casualshares/1/edit
  def edit
    @casualshare = Casualshare.find(params[:id])
  end

  # POST /casualshares
  # POST /casualshares.json
  def create
    @casualshare = Casualshare.new(params[:casualshare])
    @casualshare.user_id = current_user.id
    respond_to do |format|
      if @casualshare.save
        format.html { redirect_to @casualshare, notice: 'Casualshare was successfully created.' }
        format.json { render json: @casualshare, status: :created, location: @casualshare }
      else
        format.html { render action: "new" }
        format.json { render json: @casualshare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /casualshares/1
  # PUT /casualshares/1.json
  def update
    @casualshare = Casualshare.find(params[:id])

    respond_to do |format|
      if @casualshare.update_attributes(params[:casualshare])
        format.html { redirect_to @casualshare, notice: 'Casualshare was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @casualshare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casualshares/1
  # DELETE /casualshares/1.json
  def destroy
    @casualshare = Casualshare.find(params[:id])
    @casualshare.destroy

    respond_to do |format|
      format.html { redirect_to casualshares_url }
      format.json { head :ok }
    end
  end
end

app/helpers/casualshares_helper.rb
module CasualsharesHelper
end

app/views/casualshares/_form.html.erb
 <% @places = Place.all %>
 <% cou = @places.count %>
 <% arr = Array.new(10) { Array.new(2) } %>
 <% for n in 1..10 %>
 <% arr[n-1][0] = @places[n-1].placename %>
 <% arr[n-1][1] = n %>
 <% end %>
 <% arr %>

<%= form_for(@casualshare) do |f| %>
  <% if @casualshare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@casualshare.errors.count, "error") %> prohibited this casualshare from being saved:</h2>

      <ul>
      <% @casualshare.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :source_id %><br />
    <%= f.select(:source_id, arr ) %>
  </div>
  <div class="field">
    <%= f.label :destination_id %><br />
    <%= f.select(:destination_id, arr ) %>
  </div>
  <div class="field">
    <%= f.label :starttime %><br />
    <%= f.datetime_select :starttime %>
  </div>
  <div class="field">
    <%= f.label :endtime %><br />
    <%= f.datetime_select :endtime %>
  </div>
  <div class="field">
    <%= f.label :vehicle %><br />
    <%= f.text_field :vehicle %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :numofpassengers %><br />
    <%= f.number_field :numofpassengers %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/casualshares/edit.html.erb
<h1>Editing casualshare</h1>

<%= render 'form' %>

<%= link_to 'Show', @casualshare %> |
<%= link_to 'Back', casualshares_path %>

app/views/casualshares/index.html.erb
<h1>Casual Shares</h1>

<table border=1 width=1000>


<% @casualshares.each do |casualshare| %>
  <tr>
    <td> 
	<p> Created By : <%= casualshare.user.firstname %>  <br/>
	<b> Source : </b><%= Place.find(casualshare.source_id).placename %> |
	<b> Destination : </b><%= Place.find(casualshare.destination_id).placename %><br/>
        <b> Starting Time :</b><%= casualshare.starttime %> |
        <b> Reaching Time :</b><%= casualshare.endtime %><br/><br/>
        <%= link_to 'Show', casualshare %> | 
        <%= link_to 'Edit', edit_casualshare_path(casualshare) %> |
        <%= link_to 'Destroy', casualshare, confirm: 'Are you sure?', method: :delete %></p>
    </td>	
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Casualshare', new_casualshare_path %>

app/views/casualshares/new.html.erb
<h1>New casualshare</h1>

<%= render 'form' %>

<%= link_to 'Back', casualshares_path %>

app/views/casualshares/show.html.erb
<table width=1000 align=center border=0><tr><td width=65% valign=top>
<p>
  <b>User:</b>
  <%= @casualshare.user.firstname %>
</p>

<p>
  <b>Source:</b>
  <%= Place.find(@casualshare.source_id).placename %>
</p>

<p>
  <b>Destinatoin:</b>
  <%= Place.find(@casualshare.destination_id).placename %>
</p>

<p>
  <b>Starttime:</b>
  <%= @casualshare.starttime %>
</p>

<p>
  <b>Endtime:</b>
  <%= @casualshare.endtime %>
</p>

<p>
  <b>Vehicle:</b>
  <%= @casualshare.vehicle %>
</p>

<p>
  <b>Amount:</b>
  <%= @casualshare.amount %>
</p>

<p>
  <b>Numofpassengers:</b>
  <%= @casualshare.numofpassengers %>
</p>

<p>
  <b>Details:</b>
  <%= @casualshare.details %>
</p>


<%= link_to 'Edit', edit_casualshare_path(@casualshare) %> |
<%= link_to 'Back', casualshares_path %>

</td><td>
<%= render 'shared/casualsubscription_form' %>

<% unless @casualsubscriptions.empty? %>

<table class="microposts" style="text-align:left;" border=1 cellspacing=0 width=400>
<%= render @casualsubscriptions %>
</table>

<% end %>
</td></tr>
<tr><td>
<br/><hr />
<%= render 'shared/casualcomment_form' %>

<% unless @casualcomments.empty? %>

<table class="microposts" style="text-align:left;" border=1 cellspacing=0 width=400>
<%= render @casualcomments %>
</table>
<% end %>

</td></tr>

</table>